# build environment
FROM node:16-alpine3.17 as builder

COPY header /header

WORKDIR /app

COPY react/package.json .
COPY react/package-lock.json .

RUN npm install

COPY react .

RUN npm run build

# production environment
FROM nginx:alpine

COPY nginx-app.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
